### PR TITLE
Embed SonarC# 8.8 and SonarVB 8.8

### LINKED ISSUE #1445: Embed SonarC# 8.8 and SonarVB 8.8
Release notes: https://github.com/SonarSource/sonar-dotnet/releases/tag/8.8.0.18411

### PR DESCRIPTION
**Pull request by duncanp-sonar**
Fixes #1445

### CODE REVIEW

**Comment by rita-g-sonarsource** [comment]
@duncanp-sonar why not into branch-improveCM?

**Comment by duncanp-sonar** [comment]
> @duncanp-sonar why not into branch-improveCM?

What's the benefit?

**Comment by rita-g-sonarsource** [comment]
> > @duncanp-sonar why not into branch-improveCM?
> 
> What's the benefit?

The issue belongs in that sprint and that branch 🤷

**Comment by duncanp-sonar** [comment]
In practical terms I don't think it makes much difference which branch we merge this commit to since all of the tickets are going to be in the same release, and we're going to have to move all of the tickets from the current milestone into the "Improve CM" milestone so they are included in the generated release notes.

Everything from `branch-furtherCM` is going to be merged into `branch-improveCM` later today (hopefully).

**Pull request merged**
