### PR TITLE
Add new CCT models CCCat, CCAtt, (SwQual, SwQualSeverity)[] to IRuleInfo

### LINKED ISSUE #4740: Add new CCT models `CCCat, CCAtt, (SwQual, SwQualSeverity)[]` to IRuleInfo

### PR DESCRIPTION
**Pull request by ugras-ergun-sonarsource**
fixes #4740

### CODE REVIEW

**Comment by georgii-borovinskikh-sonarsource** [comment]
This is marked as draft still. I looked at it. Looks good. One question though: what do we do with rules that don't have any newCCT values? We talked about setting some defaults. Are you planning to add that in a different PR?

**Review by georgii-borovinskikh-sonarsource — COMMENTED** [review]
LGTM. Just a question about defaults

**Review by georgii-borovinskikh-sonarsource — APPROVED** [review]
LGTM. Just a question about defaults

**Comment by ugras-ergun-sonarsource** [comment]
> 

We need to discuss this with Marco and decide what to show as default. Maybe we can do something in UI.

**Pull request merged**
